# Generated by Django 4.1.3 on 2023-12-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, db_column='account_application_id', primary_key=True, serialize=False)),
                ('mobile_no', models.IntegerField()),
                ('email_id', models.CharField(max_length=250)),
                ('is_otp_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('is_application_processed', models.BooleanField(default=False)),
                ('is_application_draft', models.BooleanField(default=False)),
                ('etos_customer_id', models.IntegerField(default=None, null=True)),
            ],
            options={
                'db_table': 'account_opening_data',
            },
        ),
    ]
