# Generated by Django 5.0.6 on 2024-07-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountopeningmodel',
            old_name='is_application_draft',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='accountopeningmodel',
            old_name='is_application_processed',
            new_name='is_email_id_verified',
        ),
        migrations.RemoveField(
            model_name='accountopeningmodel',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='company_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='email_activation_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='email_activation_key_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='investor_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('investor', 'Investor')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='pass_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='user_title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='accountopeningmodel',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('investor', 'Investor')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountopeningmodel',
            name='email_id',
            field=models.EmailField(max_length=250, unique=True),
        ),
    ]
