# Generated by Django 5.0.6 on 2024-07-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0002_rename_is_application_draft_accountopeningmodel_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email', models.EmailField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('activation_key', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('verification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('mobile', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('verification', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mobiles',
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('activationnum', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_opener.email')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_opener.mobile')),
            ],
            options={
                'db_table': 'activations',
            },
        ),
    ]
