# Generated by Django 5.0.6 on 2024-07-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0003_email_mobile_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_registration_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('usertype', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.BooleanField(default=False)),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_opener.investor')),
            ],
            options={
                'db_table': 'user_types',
            },
        ),
    ]
