# Generated by Django 5.0.6 on 2024-07-02 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0004_investor_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETOSCust',
            fields=[
                ('cust_id', models.AutoField(db_column='account_application_id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_title', models.CharField(blank=True, max_length=10, null=True)),
                ('app_passcode', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_opening_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('etos_customer_id', models.IntegerField(default=None, null=True)),
                ('activation', models.ForeignKey(blank=True, db_column='activation', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_opener.activation')),
                ('email_id', models.ForeignKey(db_column='email_id', on_delete=django.db.models.deletion.CASCADE, to='account_opener.email')),
                ('investor_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_opener.investor')),
                ('mobile_number', models.ForeignKey(blank=True, db_column='mobile_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='account_opener.mobile')),
                ('user_type', models.ForeignKey(db_column='user_type', on_delete=django.db.models.deletion.CASCADE, to='account_opener.usertype')),
            ],
            options={
                'db_table': 'ETOS_customers',
            },
        ),
    ]
