# Generated by Django 5.0.6 on 2024-07-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0005_etoscust'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ETOSCust',
            new_name='ETOSCustomer',
        ),
        migrations.RemoveField(
            model_name='investor',
            name='company_name',
        ),
    ]
