# Generated by Django 5.0.6 on 2024-07-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0006_rename_etoscust_etoscustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='investor_type',
            field=models.CharField(choices=[('company', 'Company'), ('individual', 'Individual')], default='individual', max_length=10),
        ),
    ]
