# Generated by Django 5.0.6 on 2024-07-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_opener', '0007_investor_investor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
